version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6080:80"  # Exposes port 80 for HTTP traffic
      - "6443:443"  # Exposes port 443 for HTTPS traffic
    volumes:
      - /u01/mydev/containers-fs-layout/nginx/etc/nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
      - /u01/mydev/containers-fs-layout/nginx/data/html:/usr/share/nginx/html  # Mount directory for serving static content
      - /u01/mydev/containers-fs-layout/nginx/data:/data
    restart: always
