version: '3.7'

services:
  nginx:
    image: nginx:1.0-amd64
    container_name: nginx
    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./usr/share/nginx/html/infra:/usr/share/nginx/html/infra"
      - "/u01/mydev/containers-fs-layout/nginx/data/logs:/var/log/nginx"
    ports:
      - "18080:18080"
    expose:
      - 18080
    restart: always
    networks:
      - web-net

networks:
  web-net:
    external:
      name: mgmt-net

