version: '3.7'

services:
  nginx:
    image: soporenet-nginx:latest-amd64
    container_name: nginx
    volumes:
      - "./etc/nginx/includes/signin.sandbox.sopore.net.conf:/etc/nginx/includes/signin.sandbox.sopore.net.conf"
      - "./etc/nginx/conf.d/http.conf:/etc/nginx/conf.d/http.conf"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"
      - "/u01/mydev/containers-fs-layout/nginx/data/logs:/var/log/nginx"
    ports:
      - "8080:80"
    expose:
      - 80
    restart: always
    networks:
      - web-net

networks:
  web-net:
    external:
      name: mgmt-net

