version: '3.7'

services:
  nginx:
    image: docker.io/soporenet/nginx:1.0
    container_name: nginx
    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./usr/share/nginx/html/infra:/usr/share/nginx/html/infra"
      - "/u01/mydev/containers-fs-layout/nginx/data/logs:/var/log/nginx"
    ports:
      - "8080:80"
    expose:
      - 8080
    restart: always
    networks:
      - web-net

networks:
  web-net:
    external:
      name: mgmt-net

